/**
 * Built-in connector catalogue — wraps existing adapters; does not invent OAuth.
 * Docs URLs / restrictions are factual as of verification dates below.
 */

import type { ConnectorDefinition } from "@/services/connectors/types";

export const CONNECTOR_DEFINITIONS: ConnectorDefinition[] = [
  {
    providerKey: "manychat",
    displayName: "ManyChat",
    category: "MESSAGING",
    version: "1.0.0",
    authModes: ["api_key", "webhook_secret"],
    capabilities: ["SEND_MESSAGE", "READ_MESSAGES", "WEBHOOK_RECEIVE", "READ_CONTACTS"],
    requiredScopes: [],
    documentationUrl: "https://api.manychat.com/",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: ["Requires ManyChat Pro + API token"],
    webhookSupport: true,
    rateLimitNotes: "Provider rate limits apply; inbound webhook IP-limited in-app",
    operations: [
      {
        name: "manychat.send_message",
        capability: "SEND_MESSAGE",
        risk: "outbound_message",
        approvalRequired: true,
        idempotencySupport: true,
        providerIdempotency: "neither",
        timeoutMs: 30_000,
        retryPolicy: "transient",
        rateLimitClass: "send",
        costClass: "metered",
        piiClass: "PII",
        sideEffect: "outbound",
      },
      {
        name: "manychat.webhook_receive",
        capability: "WEBHOOK_RECEIVE",
        risk: "write_internal",
        approvalRequired: false,
        idempotencySupport: true,
        providerIdempotency: "idempotency_key",
        timeoutMs: 5_000,
        retryPolicy: "none",
        rateLimitClass: "webhook",
        costClass: "free",
        piiClass: "PII",
        sideEffect: "write_internal",
      },
    ],
  },
  {
    providerKey: "instagram",
    displayName: "Instagram",
    category: "SOCIAL",
    version: "1.0.0",
    authModes: ["oauth2"],
    capabilities: ["READ_PROFILE", "READ_OWN_CONTENT", "READ_ANALYTICS", "PUBLISH", "READ_PUBLIC_CONTENT"],
    requiredScopes: ["instagram_business_basic", "instagram_business_content_publish"],
    documentationUrl: "https://developers.facebook.com/docs/instagram-platform",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: [
      "App Review / Advanced Access for publish",
      "DMs via ManyChat — not Meta DM scopes in this product",
      "Public listening via licensed Apify, not OAuth scrape",
    ],
    webhookSupport: false,
    operations: [
      {
        name: "instagram.publish_post",
        capability: "PUBLISH",
        risk: "publish",
        approvalRequired: true,
        idempotencySupport: true,
        providerIdempotency: "lookup",
        timeoutMs: 120_000,
        retryPolicy: "transient",
        rateLimitClass: "publish",
        costClass: "metered",
        piiClass: "PUBLIC",
        sideEffect: "publish",
        requiredScopes: ["instagram_business_content_publish"],
      },
    ],
  },
  {
    providerKey: "linkedin",
    displayName: "LinkedIn",
    category: "SOCIAL",
    version: "1.0.0",
    authModes: ["oauth2"],
    capabilities: ["READ_PROFILE", "PUBLISH"],
    requiredScopes: ["openid", "profile", "w_member_social"],
    documentationUrl: "https://learn.microsoft.com/en-us/linkedin/",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: [
      "Member feed publish only in current adapter",
      "No third-party DM API",
      "No company-page posting in current adapter",
      "Token refresh not implemented in adapter",
    ],
    webhookSupport: false,
    operations: [
      {
        name: "linkedin.publish_post",
        capability: "PUBLISH",
        risk: "publish",
        approvalRequired: true,
        idempotencySupport: true,
        providerIdempotency: "lookup",
        timeoutMs: 120_000,
        retryPolicy: "transient",
        rateLimitClass: "publish",
        costClass: "metered",
        piiClass: "PUBLIC",
        sideEffect: "publish",
        requiredScopes: ["w_member_social"],
      },
    ],
  },
  {
    providerKey: "tiktok",
    displayName: "TikTok",
    category: "SOCIAL",
    version: "1.0.0",
    authModes: ["oauth2"],
    capabilities: ["READ_PROFILE", "PUBLISH"],
    requiredScopes: ["user.info.basic", "video.publish"],
    documentationUrl: "https://developers.tiktok.com/doc/content-posting-api-get-started",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: [
      "Video Direct Post only; unaudited apps often SELF_ONLY",
      "No DM API",
      "Domain verification required for pull-from-URL",
    ],
    webhookSupport: false,
    operations: [
      {
        name: "tiktok.publish_video",
        capability: "PUBLISH",
        risk: "publish",
        approvalRequired: true,
        idempotencySupport: true,
        providerIdempotency: "lookup",
        timeoutMs: 180_000,
        retryPolicy: "transient",
        rateLimitClass: "publish",
        costClass: "metered",
        piiClass: "PUBLIC",
        sideEffect: "publish",
      },
    ],
  },
  {
    providerKey: "youtube",
    displayName: "YouTube Data API",
    category: "RESEARCH",
    version: "1.0.0",
    authModes: ["api_key"],
    capabilities: ["SEARCH", "READ_PUBLIC_CONTENT", "READ_COMMENTS"],
    requiredScopes: [],
    documentationUrl: "https://developers.google.com/youtube/v3",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: ["Research/search only — not OAuth publish"],
    webhookSupport: false,
    rateLimitNotes: "Quota units; in-app RPM cap",
    operations: [
      {
        name: "youtube.search",
        capability: "SEARCH",
        risk: "read",
        approvalRequired: false,
        idempotencySupport: true,
        providerIdempotency: "neither",
        timeoutMs: 30_000,
        retryPolicy: "transient",
        rateLimitClass: "search",
        costClass: "metered",
        piiClass: "PUBLIC",
        sideEffect: "read",
      },
    ],
  },
  {
    providerKey: "tavily",
    displayName: "Tavily (web search)",
    category: "RESEARCH",
    version: "1.0.0",
    authModes: ["api_key"],
    capabilities: ["SEARCH"],
    requiredScopes: [],
    documentationUrl: "https://docs.tavily.com/",
    docsVerifiedAt: "2026-08-24",
    webhookSupport: false,
    operations: [
      {
        name: "tavily.search_web",
        capability: "SEARCH",
        risk: "read",
        approvalRequired: false,
        idempotencySupport: true,
        providerIdempotency: "neither",
        timeoutMs: 30_000,
        retryPolicy: "transient",
        rateLimitClass: "search",
        costClass: "metered",
        piiClass: "PUBLIC",
        sideEffect: "read",
      },
    ],
  },
  {
    providerKey: "apify",
    displayName: "Apify (licensed social listen)",
    category: "RESEARCH",
    version: "1.0.0",
    authModes: ["api_key"],
    capabilities: ["SEARCH", "READ_PUBLIC_CONTENT"],
    requiredScopes: [],
    documentationUrl: "https://docs.apify.com/",
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: [
      "Licensed scrape actors only",
      "Not a substitute for platform OAuth publish",
      "Facebook intentionally omitted",
    ],
    webhookSupport: false,
    operations: [
      {
        name: "apify.search_public",
        capability: "SEARCH",
        risk: "read",
        approvalRequired: false,
        idempotencySupport: true,
        providerIdempotency: "neither",
        timeoutMs: 120_000,
        retryPolicy: "transient",
        rateLimitClass: "search",
        costClass: "expensive",
        piiClass: "PUBLIC",
        sideEffect: "read",
      },
    ],
  },
  {
    providerKey: "booking",
    displayName: "Booking (link + webhook)",
    category: "BOOKING",
    version: "1.0.0",
    authModes: ["webhook_secret"],
    capabilities: ["WEBHOOK_RECEIVE", "CREATE_EVENT", "READ_CALENDAR"],
    requiredScopes: [],
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: [
      "Not full Calendly/Cal.com OAuth calendar sync",
      "Link append + inbound webhook normalisation only",
    ],
    webhookSupport: true,
    operations: [
      {
        name: "booking.webhook_receive",
        capability: "WEBHOOK_RECEIVE",
        risk: "write_internal",
        approvalRequired: false,
        idempotencySupport: true,
        providerIdempotency: "idempotency_key",
        timeoutMs: 5_000,
        retryPolicy: "none",
        rateLimitClass: "webhook",
        costClass: "free",
        piiClass: "PII",
        sideEffect: "write_internal",
      },
    ],
  },
  {
    providerKey: "email_smtp",
    displayName: "Email (SMTP)",
    category: "EMAIL",
    version: "1.0.0",
    authModes: ["env"],
    capabilities: ["SEND_EMAIL"],
    requiredScopes: [],
    docsVerifiedAt: "2026-08-24",
    commercialRestrictions: ["Report/export send; no inbox sync"],
    webhookSupport: false,
    operations: [
      {
        name: "email.send",
        capability: "SEND_EMAIL",
        risk: "outbound_message",
        approvalRequired: false,
        idempotencySupport: false,
        providerIdempotency: "neither",
        timeoutMs: 30_000,
        retryPolicy: "transient",
        rateLimitClass: "send",
        costClass: "cheap",
        piiClass: "PII",
        sideEffect: "outbound",
      },
    ],
  },
];

export function getConnectorDefinition(providerKey: string): ConnectorDefinition | null {
  return CONNECTOR_DEFINITIONS.find((c) => c.providerKey === providerKey) ?? null;
}

export function listConnectorDefinitions(): ConnectorDefinition[] {
  return CONNECTOR_DEFINITIONS;
}
